"""empty message

Revision ID: 9b203713254a
Revises: 
Create Date: 2024-08-24 15:08:00.355845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b203713254a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('days_subscribe', sa.Integer(), nullable=False),
    sa.Column('test_subscribe', sa.Boolean(), nullable=False),
    sa.Column('type_change_open', sa.Float(), nullable=False),
    sa.Column('type_many_lot', sa.Float(), nullable=False),
    sa.Column('type_change_volume', sa.Float(), nullable=False),
    sa.Column('MSNG', sa.Boolean(), nullable=False),
    sa.Column('POSI', sa.Boolean(), nullable=False),
    sa.Column('YNDX', sa.Boolean(), nullable=False),
    sa.Column('ALRS', sa.Boolean(), nullable=False),
    sa.Column('AFLT', sa.Boolean(), nullable=False),
    sa.Column('BSPB', sa.Boolean(), nullable=False),
    sa.Column('VTBR', sa.Boolean(), nullable=False),
    sa.Column('GAZP', sa.Boolean(), nullable=False),
    sa.Column('GMKN', sa.Boolean(), nullable=False),
    sa.Column('LEAS', sa.Boolean(), nullable=False),
    sa.Column('EUTR', sa.Boolean(), nullable=False),
    sa.Column('AQUA', sa.Boolean(), nullable=False),
    sa.Column('IRAO', sa.Boolean(), nullable=False),
    sa.Column('LENT', sa.Boolean(), nullable=False),
    sa.Column('LSRG', sa.Boolean(), nullable=False),
    sa.Column('LKOH', sa.Boolean(), nullable=False),
    sa.Column('MVID', sa.Boolean(), nullable=False),
    sa.Column('MTLR', sa.Boolean(), nullable=False),
    sa.Column('CBOM', sa.Boolean(), nullable=False),
    sa.Column('VKCO', sa.Boolean(), nullable=False),
    sa.Column('GEMC', sa.Boolean(), nullable=False),
    sa.Column('MAGN', sa.Boolean(), nullable=False),
    sa.Column('MOEX', sa.Boolean(), nullable=False),
    sa.Column('MBNK', sa.Boolean(), nullable=False),
    sa.Column('MTSS', sa.Boolean(), nullable=False),
    sa.Column('NLMK', sa.Boolean(), nullable=False),
    sa.Column('BELU', sa.Boolean(), nullable=False),
    sa.Column('NVTK', sa.Boolean(), nullable=False),
    sa.Column('PIKK', sa.Boolean(), nullable=False),
    sa.Column('PLZL', sa.Boolean(), nullable=False),
    sa.Column('RENI', sa.Boolean(), nullable=False),
    sa.Column('ROSN', sa.Boolean(), nullable=False),
    sa.Column('FEES', sa.Boolean(), nullable=False),
    sa.Column('RTKM', sa.Boolean(), nullable=False),
    sa.Column('RUAL', sa.Boolean(), nullable=False),
    sa.Column('HYDR', sa.Boolean(), nullable=False),
    sa.Column('RNFT', sa.Boolean(), nullable=False),
    sa.Column('SMLT', sa.Boolean(), nullable=False),
    sa.Column('SBER', sa.Boolean(), nullable=False),
    sa.Column('CHMF', sa.Boolean(), nullable=False),
    sa.Column('SGZH', sa.Boolean(), nullable=False),
    sa.Column('SELG', sa.Boolean(), nullable=False),
    sa.Column('AFKS', sa.Boolean(), nullable=False),
    sa.Column('SVCB', sa.Boolean(), nullable=False),
    sa.Column('FLOT', sa.Boolean(), nullable=False),
    sa.Column('TATN', sa.Boolean(), nullable=False),
    sa.Column('TGKA', sa.Boolean(), nullable=False),
    sa.Column('TCSG', sa.Boolean(), nullable=False),
    sa.Column('PHOR', sa.Boolean(), nullable=False),
    sa.Column('ELFV', sa.Boolean(), nullable=False),
    sa.Column('ENPG', sa.Boolean(), nullable=False),
    sa.Column('SFIN', sa.Boolean(), nullable=False),
    sa.Column('UPRO', sa.Boolean(), nullable=False),
    sa.Column('MTLRP', sa.Boolean(), nullable=False),
    sa.Column('TRNFP', sa.Boolean(), nullable=False),
    sa.Column('TATNP', sa.Boolean(), nullable=False),
    sa.Column('SBERP', sa.Boolean(), nullable=False),
    sa.Column('RTKMP', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    op.drop_table('users')
    # ### end Alembic commands ###
